name: C++ CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-gcc, windows-mingw]
        include:
          - platform: ubuntu-gcc
            os: ubuntu-latest
            compiler: g++
          - platform: windows-mingw
            os: windows-latest
            compiler: x86_64-w64-mingw32-g++

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ build-essential

      - name: Install MinGW (Windows)
        if: matrix.platform == 'windows-mingw'
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} ..
          cmake --build . --config Release

      - name: Run tests
        run: |
          cd build
          chmod +x ../run-test-data.sh
          ../run-test-data.sh ./task  # Используем путь к скомпилированному бинарнику
        working-directory: ${{ github.workspace }}