name: C++ Compilation Check

on: [push, pull_request]

jobs:
  check-compilation:
    strategy:
      matrix:
        platform: [ubuntu-gcc, windows-mingw]
        include:
          - platform: ubuntu-gcc
            os: ubuntu-latest
            compiler: g++
            build_dir: linux-build
          - platform: windows-mingw
            os: windows-latest
            compiler: x86_64-w64-mingw32-g++
            build_dir: windows-build

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install GCC (Ubuntu)
        if: matrix.platform == 'ubuntu-gcc'
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Install MinGW (Windows)
        if: matrix.platform == 'windows-mingw'
        run: choco install mingw -y --no-progress

      - name: Configure with CMake
        run: |
          mkdir ${{ matrix.build_dir }}
          cd ${{ matrix.build_dir }}
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} ..

      - name: Build project
        run: |
          cd ${{ matrix.build_dir }}
          cmake --build . --config Release